### PR TITLE
Add scanOnce/callback queue status

### PR DESCRIPTION
**Pull request by mark0n**
Reports data about scanOnce and callback queue size and usage.

This PR requires a few [modifications to EPICS Base](https://code.launchpad.net/~info-martin-konrad/epics-base/+git/epics-base/+merge/352918).

### CODE REVIEW

**Comment by mark0n** [comment]
I'm assuming that my patch will make it into EPICS Base 3.16.2. If that's not the case I might need to update the `if` statements that short-circuit the calls to the new EPICS Base functions.

**Comment by anjohnson** [comment]
This PR does now build successfully against the just-released 3.16.2 version of Base, but it needs to be modified so it doesn't break when built against earlier versions that don't provide the new *QueueStats APIs. Check the Travis-CI build logs for details.

**Comment by mark0n** [comment]
@anjohnson, thanks for the heads up. With my latest modifications it builds fine against older EPICS Base versions.

**Comment by anjohnson** [comment]
You could use this expression instead, since there will be no further 3.16 releases:
```C
#if (EPICS_VERSION_INT == VERSION_INT(3, 16, 2, 0)) || (EPICS_VERSION_INT >= VERSION_INT(7, 0, 2, 0))
```
Might be worth making that into a macro instead of pasting it throughout the source code though.

**Comment by mark0n** [comment]
Ah, good catch. Done.

**Pull request merged**
