### PR TITLE
Added the temperature monitoring of Thermal Zone0 

### PR DESCRIPTION
**Pull request by jeonghanlee**
Hi Stephanie,

  I added the temperature monitoring PV of Thermal Zone0 for any Linux distribution system. I tested it with Raspberry Pi and typical notebooks. Please check them and let me know what you think. I also changed _SC_NPROCESSORS_CONF with _SC_NPROCESSORS_ONLN because ONLN is more useful than CONF, I think. 

 Thanks,
  Han

### CODE REVIEW

**Comment by ralphlange** [comment]
I like the general idea.

However, I would prefer two things a bit different:

1. The no-of-processors related change should be in a separate, properly named commit.
2. The unit of the temperature should be something more useful than milli-Celsius. (It's mapped to an ai record, in the end.) I can see two ways to do that:
  1. *Easy:* Convert to Celsius in the routine that converts from int to double.
  2. *Not that easy:* Change the code to write the integer into the ai record's RVAL field, and do the linear conversion using the ai record's built-in mechanism. (Remember the device support's return value has to be different for activating the conversion.)

  The second option would allow an easy change between C and F units. (Might be interesting for US users. We should probably have the Fahrenheit conversion factors commented out in the database.)

**Comment by jeonghanlee** [comment]
Hi Ralph,

  As you know, this is the first time to do "pull requests"  to any EPICS modules, so please guide me how to resolve them, please remember that I am super-naive person who has no experience on EPICS.  Should I cancel or withdraw this request and then what kind of procedure should I follow for 1 and 2 separately?

  Yes, the unit - mili-Celsius is weird, I agreed. I spent few hours actually, to think what would be better unit  for EGU, and then I simply decided the same unit which Linux Kernel  uses, that is the mili-Celsius. :)

**Comment by ralphlange** [comment]
In general:
All updates you push to this branch will become part of the pull request.
So you can react to comments and suggestions and fix or further develop the feature until it is approved for merging.

In this case:
IMHO it seems appropriate to redo/regroup some of the commits, in order to separate things that do not belong together. This cannot be done on the existing branch, as these operations break the branch history of existing commits. This situation is better handled by creating a new branch on which you can cherry-pick, regroup, relabel etc. as you prefer, then pushing the new branch when you're happy with it and creating a new pull request, superseding this one.

**Comment by ralphlange** [comment]
The [workflow](https://github.com/areaDetector/areaDetector/wiki/areaDetector-Git-Workflows) that @MarkRivers pointed you to is a good start.

Some general things related to commits:
- A commit should contain changes that belong together. Git's interactive rebase command is a way to rearrange, reorder, and regroup commits. *Note:* Doing so changes the history of the branch. You should do that before pushing to a public repository. If a "messy" branch is already published, push the cleaned-up version to a new public branch.
- The module should at least be compiling. (Don't push before you at least successfully compiled the module. The fix to get it back to compile should be appended to the commit that broke it.)
- Commit messages should be concise and comprehensive, telling people without detail knowledge what the commit contains. (On this branch, "try to understand..." is a bad example, "put sys_zonetemp into LOAD_TYPE" is a good one.)
- Many projects have additional conventions regarding commit messages. Look at the existing commits and ask maintainers if in doubt.

**Comment by jeonghanlee** [comment]
Thank you, Ralph :)

**Comment by jeonghanlee** [comment]
Ralph, I realized, I am not that expert to do what you explained. So, I will re-do from scratch.

**Comment by ralphlange** [comment]
No worries.
I've been in situations more than a few times where - looking back - I realized starting from scratch would have been easier and faster.
Whatever works best for you!

**Comment by jeonghanlee** [comment]
I did it from scratch. :)  Please look at them and let me know. I think, we need to discuss "the temperature unit" in https://github.com/epics-modules/iocStats/pull/7

**Pull request closed without merging**
