### PR TITLE
Update Travis to use ci-scripts

### PR DESCRIPTION
**Pull request by MJGaughran**
RTEMS 4.10 fails to find rtemsReboot(), and msi is not available for R3.14*

### CODE REVIEW

**Comment by ralphlange** [comment]
MSI issue has been fixed with ci-scripts 2.2.1
https://github.com/epics-base/ci-scripts/releases

**Comment by ralphlange** [comment]
iocStats has a very busy maintainer... What's your suggestion?

**Comment by MJGaughran** [comment]
At the time this pull request was made, there were two issues:
- msi was not available for R3.14.12.3
- There was a problem with 'rtemsReboot' for RTEMS 4.10

You can see these problems in the Details screen for the failing check for this pull request.

As Ralph has mentioned above, msi has been added now. We just need to upgrade the version of ci-scripts used here. This will also allow us to merge ci-scripts into softGlue.

Unfortunately, I don't know how to fix the second issue. It's up to you if you want to ignore the RTEMS 4.10 build.

**Comment by ralphlange** [comment]
I am for update and merge.
The failing RTEMS build has a problem that is not related to this PR.

**Comment by ralphlange** [comment]
So you suggest:
- update to ci-scripts latest 2.x
- merge
- new PR for update to 3.0.1

**Comment by MJGaughran** [comment]
Is your problem that this branch is on my own fork? I can just push it to this repo, and then you can add to it.

**Comment by kmpeters** [comment]
@ralphlange, yes.

@MJGaughran, if I create a pull request to update ci-scripts to v3.0.1 and it is merged before this one, then this pull request is obsolete.  I believe your changes should be a part of the git history since you put in the time and effort to create the pull request.

**Comment by kmpeters** [comment]
This doesn't need to be merged now.  I was just trying to proactive since upgrading ci-scripts is fresh in my mind.

**Comment by MJGaughran** [comment]
I'll probably sort it out soon, I just don't want to start on this in the evening.

**Comment by simon-ess** [comment]
@MJGaughran - You didn't want to start on this "in the evening", but how about now? I have taken over maintenance of iocStats and I am looking to clean up old PRs. Is there still any need for this pull request?

**Pull request closed without merging**
